$(function(){
  function carregarLivros(){
    fetch("http://localhost:8080/bookteca-api/src/lerLivros.php").then(function(resposta){
      resposta.json().then(function(json){
        console.log(json)
          let listagem = $("#listagem")
          let coluna4 = $("<div></div>")
          coluna4.addClass("col-4")
          let card = $("<div></div>")
          card.addClass("custom-card")
          coluna4.append(card)
          let cardHeader = $("<header></header>")
          cardHeader.addClass("custom-card-header")
          card.append(cardHeader)
          let cardHeaderTitleContainer = $("<div></div>")
          cardHeaderTitleContainer.addClass("custom-card-header-container")
          let cardHeaderTitle = $("<strong></strong>")
          cardHeaderTitle.addClass("custom-card-header-title")
          cardHeaderTitle.append(json[2].titulo)
          let cardHeaderSubtitle = $("<h6></h6>")
          cardHeaderSubtitle.addClass("custom-card-header-subtitle")
          cardHeaderSubtitle.append(json[2].subtitulo)
          cardHeaderTitleContainer.append(cardHeaderTitle)
          cardHeaderTitleContainer.append(cardHeaderSubtitle)
          cardHeader.append(cardHeaderTitleContainer)
          cardHeaderIcon = $("<span></span>")
          cardHeaderIcon.addClass("custom-card-header-icon")
          cardHeader.prepend(cardHeaderIcon)
          let cardImg = $("<div></div>")
          cardImg.addClass("custom-card-img")
          cardImg.css("background-image", 'url("https://www.casadoeducador.com/imagens/produtos/publi_linguagens_expressivas-b77e303655608b39ce4ee84c09aa4303.jpg")')
          card.append(cardImg)
          //prepend tem a função de adicionar algo ao final, já o append no começo
          listagem.append(coluna4)
      })
    })
  }

  carregarLivros()
})
